laguage: node_js
cache:
  directories:
    - node_modules
    - ~/.npm  
node_js:
  - '14'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - haroldadrian@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: 'Deploy del proyecto desde travis'
  on:
    branch: master